name: dart_ffi_primes

version: 0.0.1

homepage: https://github.com/PlugFox/dart_ffi_primes

repository: https://github.com/PlugFox/dart_ffi_primes

issue_tracker: https://github.com/PlugFox/dart_ffi_primes/issues

funding:
  - https://www.buymeacoffee.com/plugfox
  - https://www.patreon.com/plugfox
  - https://boosty.to/plugfox

topics:
  - fizzbuzz
  - dart
  - algorithm
  - cli
  - benchmark

platforms:
  linux:
  macos:
  windows:

executables:
  - tool/compile.dart

environment:
  sdk: ">=3.6.0 <4.0.0"

# dart pub upgrade --major-versions --tighten
dependencies:
  args: ^2.6.0
  ffi: ^2.1.3
  meta: ^1.16.0
  path: ^1.9.1
  stack_trace: ^1.12.1

  # Benchmarking
  benchmark_harness: ^2.3.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
  vm_service: ^15.0.0
  fake_async: ^1.3.2
  ffigen: ^15.0.0

ffigen:
  name: 'PrimesLibrary'
  description: 'A library for generating prime numbers.'
  output: 'lib/src/primes_ffi.g.dart'
  headers:
    entry-points:
      - 'library/prime.h'
  preamble: |
    // This file is generated by ffigen.